name: Build unsigned AAB (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5' 
          channel: 'stable'
          
      - name: Install Android SDK components (NDK + build-tools)
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" >/dev/null || true
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620" "cmake;3.10.2.4988404"

      - name: Expose NDK llvm-strip on PATH
        run: |
          # set this to the exact NDK folder your sdkmanager installed (check previous logs)
          NDK_VER="23.1.7779620"
          ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
          ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/$NDK_VER"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
          ls -l "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" || true


      - name: Restore pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Ensure JDK and remove bad org.gradle.java.home
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Remove org.gradle.java.home if present (CI-safe)
        run: |
          sed -i '/org.gradle.java.home/d' gradle.properties || true
          sed -i '/org.gradle.java.home/d' android/gradle.properties || true
          sed -i '/org.gradle.java.home/d' android/local.properties || true

      - name: Get dependencies
        run: flutter pub get

      - name: Build unsigned app bundle (AAB)
        run: |
          flutter build appbundle --release \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-unsigned
          path: build/app/outputs/bundle/release/*.aab